In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from mlxtend.plotting import plot_decision_regions  # noqa: F401

In [8]:
dataset = pd.read_csv(r"C:\Users\kashi\OneDrive\图片\Desktop\birthday\ML\iris.data", header=None, names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'])
dataset.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [9]:
dataset.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [10]:
x = dataset.iloc[:, :-1]
y = dataset["species"]

In [11]:
from sklearn.tree import plot_tree

In [12]:
plt.figure(figsize=(20,20))
plot_tree(dt)
plt.show()

NameError: name 'dt' is not defined

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test  = train_test_split(x,y,test_size = 0.2, random_state =42)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth=3)#pruning krna ho kr ye pre pruning hai

In [ ]:
dt.fit(x_train, y_train)

In [ ]:
dt.score(x_test, y_test)

In [ ]:
dt.score(x_train, y_train)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt1 = DecisionTreeClassifier(criterion="entropy")

In [ ]:
dt1.fit(x_train, y_train)

In [ ]:
dt1.score(x_test, y_test)

#### Post pruning

In [ ]:
for i in range(1,10):
    dt2 = DecisionTreeClassifier(max_depth=i)
    dt2.fit(x_train, y_train)
    print(f"Max Depth: {i}, Training Score: {dt2.score(x_train, y_train)}, Test Score: {dt2.score(x_test, y_test)}")

#### Decision tree (regression)

In [ ]:
import seaborn as sns
sns.pairplot(data=dataset)
plt.show

In [ ]:
dataset.head()

In [ ]:
x = dataset.iloc[:, :-1]
y = dataset["species"]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.tree import DecisionTreeRegressor,plot_tree

In [ ]:
dr= DecisionTreeRegressor()
dr.fit(x_train, y_train)
dr.score(x_test, y_test)

In [ ]:
plot_tree(dr)
plt.show()

## KNN

KNN ka logic bahut human-like hai 😄

“Nearby cheezein usually similar hoti hain.”

Example:
Agar tumhare aas-paas mostly doctors hain,
to chances hain tum medical environment se related ho 👀

Machine learning me bhi same idea.

Meaning of “K”

K = number of nearest neighbors.

Example:

K = 3
K = 5

Algorithm nearby K points dekhta hai.

🔷 How KNN Works

Suppose new point classify karna hai.

Step 1

K choose karo.

Example:

K = 3
Step 2

New point aur sab training points ke beech distance calculate karo.

Usually:
👉 Euclidean Distance

use hota hai.
d=\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}


Nearest K neighbors select karo.

Step 4

Majority vote lo.

Example:
Nearest neighbors:

Dog
Dog
Cat

✅ Final prediction = Dog

🔥 Choosing K Value
Small K

Example:

K = 1

👉 Very sensitive to noise

Can overfit.

Large K

👉 Smoother predictions

But underfitting ho sakti ha

🔥 Types of Distance Metrics
1. Euclidean Distance

Most common

2. Manhattan Distance

d=∣x
2
	​

−x
1
	​

∣+∣y
2
	​

−y
1
	​

∣

3. Minkowski Distance

Generalized form.

🔥 Advantages ✅
 Simple to understand

 No training phase

 Good for small datasets

 Works for multiclass problems

 
 🔥 Disadvantages ❌
Slow for large datasets

Sensitive to noise

Feature scaling important

Memory intensive