#Handling  of dublicate data

In [1]:
import pandas as pd

In [2]:
data = {"Name": ["Alice", "Bob", "Charlie", "Alice","Sita","Veeru","krishyu","Nancy","Vaishnavi","Aman","Manas"],"Eng":[99,66,44,99,94,47,90,98,56,54,88],"Maths":[89,99,98,89,55,89,87,90,67,54,79],"Gender":[1,0,0,1,0,1,1,1,0,+1,-0]}

In [3]:
df = pd.DataFrame(data)
df

         Name  Eng  Maths  Gender
0       Alice   99     89       1
1         Bob   66     99       0
2     Charlie   44     98       0
3       Alice   99     89       1
4        Sita   94     55       0
5       Veeru   47     89       1
6     krishyu   90     87       1
7       Nancy   98     90       1
8   Vaishnavi   56     67       0
9        Aman   54     54       1
10      Manas   88     79       0

In [4]:
df["duplicated"] = df.duplicated()
df

         Name  Eng  Maths  Gender  duplicated
0       Alice   99     89       1       False
1         Bob   66     99       0       False
2     Charlie   44     98       0       False
3       Alice   99     89       1        True
4        Sita   94     55       0       False
5       Veeru   47     89       1       False
6     krishyu   90     87       1       False
7       Nancy   98     90       1       False
8   Vaishnavi   56     67       0       False
9        Aman   54     54       1       False
10      Manas   88     79       0       False

In [ ]:
df.loc[[0,3]]

In [ ]:
df.drop_duplicates()#dl krta 
df.drop_duplicates(inplace=True)#original data me dl kr deeta hai
df

### Changing of data types and handling of duplicate data

In [ ]:
df.info()

In [ ]:
df["Gender"].value_counts()#ginti karta hai kitne values kitni bar hai

In [ ]:
df["Gender"].fillna(df["Gender"].mode()[0])

In [ ]:
df["Gender"] = df["Gender"].astype("bool")#.astype data types change krta hai

In [ ]:
df.info()

# Function Transformer

FunctionTransformer kya hai?

👉 Scikit-learn ka transformer
jo custom function ko feature par apply karta hai.

Matlab:

➡️ hum apna function dete hain
➡️ sklearn usko column(s) par laga deta hai.

Kab use karte hain?

log transform

square, sqrt

custom formula

unit conversion

domain based transformation

Important point

👉 Ye feature transformation / feature engineering me aata hai
👉 Ye feature scaling nahi hai

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
sns.histplot(df["Maths"])
plt.show()
#next step ager outlier present ho fr use IQR method se remove krna pdega

Limitation

negative values me log1p fail ho sakta hai (x < -1)

wrong function → data leak / wrong distribution

In [ ]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np
ft = FunctionTransformer(np.log1p)
ft.fit(df[["Maths"]])

In [ ]:
ft.transform(df[["Maths"]])